# Importing the modules

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

# Data preprocessing

## Importing the dataset

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding the categorical data - Geography and Gender column

In [5]:
# encoding the Gender column using simple LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
print(X[:, 2])

[0 0 0 ... 0 1 0]


In [7]:
# encoding the Geography column using ColumnTransformer + OneHotEncoder 
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting the dataset into training set and test set

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
print(X_train)

[[1.0 0.0 0.0 ... 1 1 179093.26]
 [0.0 1.0 0.0 ... 1 1 195978.86]
 [0.0 0.0 1.0 ... 1 0 85891.02]
 ...
 [1.0 0.0 0.0 ... 0 0 92220.12]
 [1.0 0.0 0.0 ... 1 0 97508.04]
 [0.0 1.0 0.0 ... 1 1 53581.14]]


In [11]:
print(y_train)

[0 0 1 ... 1 1 0]


In [12]:
print(X_test)

[[0.0 1.0 0.0 ... 0 0 41788.37]
 [1.0 0.0 0.0 ... 1 1 146379.3]
 [0.0 0.0 1.0 ... 1 0 58561.31]
 ...
 [1.0 0.0 0.0 ... 1 0 33373.26]
 [1.0 0.0 0.0 ... 1 0 76755.99]
 [0.0 1.0 0.0 ... 1 1 107674.3]]


In [13]:
print(y_test)

[0 0 0 ... 1 1 1]


## Feature scaling

In [14]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
print(X_train)

[[ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267  0.97481699
   1.36766974]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
   1.6612541 ]
 [-0.99850112 -0.57946723  1.73494238 ...  0.64920267 -1.02583358
  -0.25280688]
 ...
 [ 1.00150113 -0.57946723 -0.57638802 ... -1.54035103 -1.02583358
  -0.1427649 ]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -0.05082558]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
  -0.81456811]]


In [16]:
print(X_test)

[[-0.99850112  1.72572313 -0.57638802 ... -1.54035103 -1.02583358
  -1.01960511]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267  0.97481699
   0.79888291]
 [-0.99850112 -0.57946723  1.73494238 ...  0.64920267 -1.02583358
  -0.72797953]
 ...
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -1.16591585]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -0.41163463]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
   0.12593183]]


# Building the ANN

In [17]:
ann = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=6, activation='relu'),
    tf.keras.layers.Dense(units=6, activation='relu'),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

# Training the ANN

In [18]:
# compiling the ANN with Stochastic Gradient Descent
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# training the ANN on the training set
ann.fit(X_train, y_train, batch_size=64, epochs=100)

Epoch 1/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7934 - loss: 0.5188
Epoch 2/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4709
Epoch 3/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4508
Epoch 4/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4402
Epoch 5/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7987 - loss: 0.4334
Epoch 6/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8048 - loss: 0.4280
Epoch 7/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8052 - loss: 0.4235
Epoch 8/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8081 - loss: 0.4192
Epoch 9/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8087 - loss: 0.4152
Epoch 10/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8102 - loss: 0.4115
Epoch 11/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8135 - loss: 0.4077
Epoch 12/100
125/125 ━━━━━━━━━━━━━━━━━━━━

# Predicting the test set results

In [21]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5 # hence i use a Sigmoid activation function in the output layer (0 < values < 1)
                      # and the result could be continious, i have to implement this code to make target values binary (0 or 1) 

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step


# Making the confusion matrix and accuracy score

In [22]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1530   77]
 [ 204  189]]


0.8595